import { createRouter,createWebHistory } from "vue-router"

//编写路由设置 并导出
export const router = createRouter({
    history:createWebHistory(),
    routes:[
        {
            path:'/',
            component:()=>import('../views/LoginView.vue')
        },
        {
            path:'/dashboard',
            component:()=>import('../views/DashboardView.vue'),
            children:[
                {
                    path:'role',
                    component:()=>import('../views/RoleManageView.vue')
                },
                {
                    path:'permission',
                    component:()=>import('../views/PermissionManageView.vue')
                },
                {
                    path:'user',
                    component:()=>import('../views/UserView.vue')
                },
                {
                    path:'user/:userId',
                    component:()=>import('../views/UserDetailView.vue')
                },
                {
                    path:'user/input',
                    component:()=>import('../views/UserInputView.vue')
                },
                {
                    path:'user/edit/:userId',
                    component:()=>import('../views/UserInputView.vue')
                },
                {
                    path:'activity',
                    component:()=>import('../views/ActivityView.vue')
                },
                {
                    path:'activity/:activityId',
                    component:()=>import('../views/ActivityDetailView.vue')
                },
                {
                    path:'clue',
                    component:()=>import('../views/ClueView.vue')
                },
                {
                    path:'clue/input',
                    component:()=>import('../views/ClueInputView.vue')
                },
                {
                    path:'clue/edit/:clueId',
                    component:()=>import('../views/ClueInputView.vue')
                },
                {
                    path:'clue/:clueId',
                    component:()=>import('../views/ClueDetailView.vue')
                },
                {
                    path:'customer',
                    component:()=>import('../views/CustomerView.vue')
                },
                {
                    path:'customer/input',
                    component:()=>import('../views/CustomerInputView.vue')
                },
                {
                    path:'customer/edit/:customerId',
                    component:()=>import('../views/CustomerInputView.vue')
                },
                {
                    path:'customer/:customerId',
                    component:()=>import('../views/CustomerDetailView.vue')
                },
                {
                    path:'tran',
                    component:()=>import('../views/TranView.vue')
                },
                {
                    path:'tran/input',
                    component:()=>import('../views/TranInputView.vue')
                },
                {
                    path:'tran/edit/:tranId',
                    component:()=>import('../views/TranInputView.vue')
                },
                {
                    path:'tran/:tranId',
                    component:()=>import('../views/TranDetailView.vue')
                },
                {
                    path:'chart/performance',
                    component:()=>import('../views/chart/PerformanceAnalysisView.vue')
                },
                {
                    path:'chart/analysis',
                    component:()=>import('../views/chart/DataAnalysisView.vue')
                },
                {
                    path:'',
                    redirect:'/dashboard/chart/performance'
                },
            ]
        }
    ]
})